# Generated by Django 4.1.1 on 2022-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('shop', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('time_date', models.DateTimeField()),
            ],
        ),
    ]
